
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class MenuUlti extends javax.swing.JFrame {

    /**
     * Creates new form MenuUlti
     */
    public MenuUlti() {
        initComponents();
        this.setTitle("Settings");
        this.setSize(513,335);
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        ImageIcon img = new ImageIcon("src/Icon/Pokeball.png");
        this.setIconImage(img.getImage());
        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        
//        for (int i = 0; i < Battle.getTim2().size(); i++) {
//            if(i==0){
//                poke1.setIcon(Battle.getTim2().get(i).getGambar());
//                button1.setEnabled(true);
//                button1.setText(Battle.getTim2().get(i).getNama());
//            }else if(i==1){
//                poke2.setIcon(Battle.getTim2().get(i).getGambar());
//                button2.setEnabled(true);
//                button2.setText(Battle.getTim2().get(i).getNama());
//            }else if(i==2){
//                poke3.setIcon(Battle.getTim2().get(i).getGambar());
//                button3.setEnabled(true);
//                button3.setText(Battle.getTim2().get(i).getNama());
//            }
//            
//            
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        poke3 = new javax.swing.JButton();
        poke1 = new javax.swing.JButton();
        poke2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setText("Pokemon 2");
        button2.setEnabled(false);
        button2.setFocusPainted(false);
        button2.setFocusable(false);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        button3.setText("Pokemon 3");
        button3.setEnabled(false);
        button3.setFocusPainted(false);
        button3.setFocusable(false);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        button1.setText("Pokemon 1");
        button1.setEnabled(false);
        button1.setFocusPainted(false);
        button1.setFocusable(false);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        poke3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pokeball.png"))); // NOI18N
        poke3.setBorder(null);
        poke3.setBorderPainted(false);
        poke3.setContentAreaFilled(false);
        poke3.setDefaultCapable(false);
        poke3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pokeball.png"))); // NOI18N
        poke3.setFocusPainted(false);
        poke3.setFocusable(false);
        poke3.setRequestFocusEnabled(false);
        getContentPane().add(poke3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 120, 120));

        poke1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pokeball.png"))); // NOI18N
        poke1.setBorder(null);
        poke1.setBorderPainted(false);
        poke1.setContentAreaFilled(false);
        poke1.setDefaultCapable(false);
        poke1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pokeball.png"))); // NOI18N
        poke1.setFocusPainted(false);
        poke1.setFocusable(false);
        poke1.setRequestFocusEnabled(false);
        getContentPane().add(poke1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 120));

        poke2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pokeball.png"))); // NOI18N
        poke2.setBorder(null);
        poke2.setBorderPainted(false);
        poke2.setContentAreaFilled(false);
        poke2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pokeball.png"))); // NOI18N
        poke2.setFocusPainted(false);
        poke2.setFocusable(false);
        poke2.setRequestFocusEnabled(false);
        getContentPane().add(poke2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 120, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:

        dispose();

    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:

        dispose();

    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUlti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUlti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUlti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUlti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUlti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton poke1;
    private javax.swing.JButton poke2;
    private javax.swing.JButton poke3;
    // End of variables declaration//GEN-END:variables
}
